### PR TITLE
Update dockerfile to use 3.8.3.redhat-00003

### PR DESCRIPTION
**Pull request by mocenas**

### CODE REVIEW

**Review by rsvoboda — APPROVED** [review]
LGTM. @fedinskiy could you pls double check?

**Comment by fedinskiy** [comment]
@mocenas I suggest you also update Mandrel version

**Comment by mocenas** [comment]
> @mocenas I suggest you also update Mandrel version

I've updated mandrel to version 22.3.5.0. Which is the latest that supports JDK 17. Do we want to go for newer java?

**Comment by rsvoboda** [comment]
We do not run native tests, so I didn't comment about Mandrel version. I'm ok to stay on 22.3.

**Pull request merged**
