### PR TITLE
Add a comment that the script file is not used for testing

### PR DESCRIPTION
**Pull request by jedla97**
As per your suggestion in QQE-908 I adding the property to disable re-runs to have more cleaner and readable logs.

### CODE REVIEW

**Comment by fedinskiy** [comment]
Hi, as far as I remember,  this script is not used now, and we should do these kind of changes in the release repo.

The PR is there: https://github.com/openshift/release/pull/55868

**Comment by rsvoboda** [comment]
@fedinskiy is this repo used by OpenShift team of everything is on their side now?

**Comment by fedinskiy** [comment]
@rsvoboda they use our dockerfile, but scripts are overloaded.

**Comment by jedla97** [comment]
Thanks for info I didn't know that. 

I added the comment there for others to pointed them to correct place.

**Review by fedinskiy — APPROVED** [review]
@jedla97 thank you for the note

I suggest, that after Interstellar release we discuss this with OCP team and switch back to using our script, since going through OCP PR process for every little thing is too much hassle.

**Comment by rsvoboda** [comment]
> @rsvoboda they use our dockerfile, but scripts are overloaded.

When did this change? Is there any PR / communication to point to?

**Comment by fedinskiy** [comment]
@rsvoboda almost from the beginning: https://github.com/openshift/release/pull/40279

**Pull request merged**
