### PR TITLE
Bump RHBQ to 3.2.10.Final-redhat-00003

### PR DESCRIPTION
**Pull request by michalvavrik**
TSIA

### CODE REVIEW

**Comment by michalvavrik** [comment]
I don't think 4.14 failure is related:

```
'curl --fail --location --progress-bar "${SDKMAN_SERVICE}/...}" > "$sdkman_zip_file"': command failed with exit code 22.
error: build error: building at STEP "RUN wget -O sdkman.s.../bin/bash sdkman.sh": while running runtime: exit status 22 
INFO[2024-02-19T12:05:52Z] Reporting job state 'failed' with reason 'executing_graph:step_failed:building_project_image' 
```

**Comment by fedinskiy** [comment]
@michalvavrik the problem, is that we can not run the full CI either. Let's try
1. Run the test later
2. Drop sdkman from the Dockerfile

**Comment by michalvavrik** [comment]
I'll do 1. for now and checkout tomorrow number 2. if necessary. I'm in no hurry. Thanks

**Review by fedinskiy — APPROVED** [review]

**Comment by fedinskiy** [comment]
@michalvavrik we now see failures in upstream CI due to this change[1]

```
[ERROR] Non-resolvable import POM: The following artifacts could not be resolved: com.redhat.quarkus.platform:quarkus-bom:pom:3.2.10.Final-redhat-00003 (absent): Could not find artifact com.redhat.quarkus.platform:quarkus-bom:pom:3.2.10.Final-redhat-00003 in red-hat-enterprise-maven-repository (https://maven.repository.redhat.com/ga/) @ line 64, column 25
```

could you take a look?
[1] https://github.com/openshift/release/pull/49128

**Comment by michalvavrik** [comment]
I can only see `2` https://maven.repository.redhat.com/ga/com/redhat/quarkus/platform/quarkus-bom/3.2.10.Final-redhat-00002/ so looks like I made some mistake. I can see that `3.2.10.Final-redhat-00003` is correct version for platform, I'll check.

**Pull request merged**
